[2025-02-18T21:41:16.604+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T21:41:16.644+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branch_dag.generate_random_number_task manual__2025-02-18T21:41:14.924806+00:00 [queued]>
[2025-02-18T21:41:16.656+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branch_dag.generate_random_number_task manual__2025-02-18T21:41:14.924806+00:00 [queued]>
[2025-02-18T21:41:16.657+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-18T21:41:16.690+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): generate_random_number_task> on 2025-02-18 21:41:14.924806+00:00
[2025-02-18T21:41:16.698+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=719) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T21:41:16.742+0000] {standard_task_runner.py:72} INFO - Started process 720 to run task
[2025-02-18T21:41:16.702+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branch_dag', 'generate_random_number_task', 'manual__2025-02-18T21:41:14.924806+00:00', '--job-id', '1025', '--raw', '--subdir', 'DAGS_FOLDER/18_branch_dag.py', '--cfg-path', '/tmp/tmpvgw0gmrt']
[2025-02-18T21:41:16.753+0000] {standard_task_runner.py:105} INFO - Job 1025: Subtask generate_random_number_task
[2025-02-18T21:41:16.992+0000] {task_command.py:467} INFO - Running <TaskInstance: branch_dag.generate_random_number_task manual__2025-02-18T21:41:14.924806+00:00 [running]> on host ab74d4d90d32
[2025-02-18T21:41:17.229+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branch_dag' AIRFLOW_CTX_TASK_ID='generate_random_number_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T21:41:14.924806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T21:41:14.924806+00:00'
[2025-02-18T21:41:17.230+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T21:41:17.273+0000] {python.py:240} INFO - Done. Returned value was: 17
[2025-02-18T21:41:17.312+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T21:41:17.313+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=branch_dag, task_id=generate_random_number_task, run_id=manual__2025-02-18T21:41:14.924806+00:00, execution_date=20250218T214114, start_date=20250218T214116, end_date=20250218T214117
[2025-02-18T21:41:17.366+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T21:41:17.443+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T21:41:17.447+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
