[2025-02-14T21:10:48.352+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T21:10:48.389+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_all_failed_dag.task3 scheduled__2025-02-12T21:33:00+00:00 [queued]>
[2025-02-14T21:10:48.413+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_all_failed_dag.task3 scheduled__2025-02-12T21:33:00+00:00 [queued]>
[2025-02-14T21:10:48.413+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-14T21:10:48.434+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task3> on 2025-02-12 21:33:00+00:00
[2025-02-14T21:10:48.446+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'trigger_all_failed_dag', 'task3', 'scheduled__2025-02-12T21:33:00+00:00', '--job-id', '798', '--raw', '--subdir', 'DAGS_FOLDER/07_trigger_all_failed_dag.py', '--cfg-path', '/tmp/tmpa4enjxdt']
[2025-02-14T21:10:48.448+0000] {standard_task_runner.py:105} INFO - Job 798: Subtask task3
[2025-02-14T21:10:48.442+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=309) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T21:10:48.452+0000] {standard_task_runner.py:72} INFO - Started process 310 to run task
[2025-02-14T21:10:48.551+0000] {task_command.py:467} INFO - Running <TaskInstance: trigger_all_failed_dag.task3 scheduled__2025-02-12T21:33:00+00:00 [running]> on host ab74d4d90d32
[2025-02-14T21:10:48.672+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_all_failed_dag' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T21:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-12T21:33:00+00:00'
[2025-02-14T21:10:48.673+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T21:10:48.695+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-14T21:10:48.697+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-02-14T21:10:48.709+0000] {subprocess.py:99} INFO - Output:
[2025-02-14T21:10:53.713+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-14T21:10:53.739+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T21:10:53.739+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=trigger_all_failed_dag, task_id=task3, run_id=scheduled__2025-02-12T21:33:00+00:00, execution_date=20250212T213300, start_date=20250214T211048, end_date=20250214T211053
[2025-02-14T21:10:53.775+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T21:10:53.791+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-14T21:10:53.793+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
