[2025-02-18T21:45:34.812+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T21:45:34.833+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branch_dag.generate_random_number_task manual__2025-02-18T21:45:33.427674+00:00 [queued]>
[2025-02-18T21:45:34.846+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branch_dag.generate_random_number_task manual__2025-02-18T21:45:33.427674+00:00 [queued]>
[2025-02-18T21:45:34.846+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-18T21:45:34.862+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): generate_random_number_task> on 2025-02-18 21:45:33.427674+00:00
[2025-02-18T21:45:34.868+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=784) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T21:45:34.870+0000] {standard_task_runner.py:72} INFO - Started process 785 to run task
[2025-02-18T21:45:34.871+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branch_dag', 'generate_random_number_task', 'manual__2025-02-18T21:45:33.427674+00:00', '--job-id', '1030', '--raw', '--subdir', 'DAGS_FOLDER/18_branch_dag.py', '--cfg-path', '/tmp/tmphhi0u14n']
[2025-02-18T21:45:34.873+0000] {standard_task_runner.py:105} INFO - Job 1030: Subtask generate_random_number_task
[2025-02-18T21:45:34.938+0000] {task_command.py:467} INFO - Running <TaskInstance: branch_dag.generate_random_number_task manual__2025-02-18T21:45:33.427674+00:00 [running]> on host ab74d4d90d32
[2025-02-18T21:45:35.058+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branch_dag' AIRFLOW_CTX_TASK_ID='generate_random_number_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T21:45:33.427674+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T21:45:33.427674+00:00'
[2025-02-18T21:45:35.059+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T21:45:35.079+0000] {python.py:240} INFO - Done. Returned value was: 27
[2025-02-18T21:45:35.108+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T21:45:35.109+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=branch_dag, task_id=generate_random_number_task, run_id=manual__2025-02-18T21:45:33.427674+00:00, execution_date=20250218T214533, start_date=20250218T214534, end_date=20250218T214535
[2025-02-18T21:45:35.166+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T21:45:35.201+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T21:45:35.203+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
