[2025-02-18T21:45:36.362+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T21:45:36.394+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branch_dag.branch_task manual__2025-02-18T21:45:33.427674+00:00 [queued]>
[2025-02-18T21:45:36.410+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branch_dag.branch_task manual__2025-02-18T21:45:33.427674+00:00 [queued]>
[2025-02-18T21:45:36.410+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-18T21:45:36.426+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2025-02-18 21:45:33.427674+00:00
[2025-02-18T21:45:36.431+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=787) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-18T21:45:36.434+0000] {standard_task_runner.py:72} INFO - Started process 788 to run task
[2025-02-18T21:45:36.434+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branch_dag', 'branch_task', 'manual__2025-02-18T21:45:33.427674+00:00', '--job-id', '1031', '--raw', '--subdir', 'DAGS_FOLDER/18_branch_dag.py', '--cfg-path', '/tmp/tmpz0ylmhal']
[2025-02-18T21:45:36.437+0000] {standard_task_runner.py:105} INFO - Job 1031: Subtask branch_task
[2025-02-18T21:45:36.491+0000] {task_command.py:467} INFO - Running <TaskInstance: branch_dag.branch_task manual__2025-02-18T21:45:33.427674+00:00 [running]> on host ab74d4d90d32
[2025-02-18T21:45:36.594+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branch_dag' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T21:45:33.427674+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T21:45:33.427674+00:00'
[2025-02-18T21:45:36.594+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-18T21:45:36.608+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-18T21:45:36.619+0000] {python.py:240} INFO - Done. Returned value was: even_number_task
[2025-02-18T21:45:36.620+0000] {branch.py:38} INFO - Branch into even_number_task
[2025-02-18T21:45:36.620+0000] {skipmixin.py:233} INFO - Following branch ('even_number_task',)
[2025-02-18T21:45:36.631+0000] {skipmixin.py:281} INFO - Skipping tasks [('odd_number_task', -1)]
[2025-02-18T21:45:36.665+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-18T21:45:36.665+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=branch_dag, task_id=branch_task, run_id=manual__2025-02-18T21:45:33.427674+00:00, execution_date=20250218T214533, start_date=20250218T214536, end_date=20250218T214536
[2025-02-18T21:45:36.729+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T21:45:36.758+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-18T21:45:36.760+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
