[2025-02-21T20:18:29.593+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T20:18:29.618+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hooks.print_result_task manual__2025-02-21T20:17:13.249656+00:00 [queued]>
[2025-02-21T20:18:29.630+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hooks.print_result_task manual__2025-02-21T20:17:13.249656+00:00 [queued]>
[2025-02-21T20:18:29.630+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-21T20:18:29.647+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): print_result_task> on 2025-02-21 20:17:13.249656+00:00
[2025-02-21T20:18:29.652+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=301) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-21T20:18:29.654+0000] {standard_task_runner.py:72} INFO - Started process 309 to run task
[2025-02-21T20:18:29.654+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hooks', 'print_result_task', 'manual__2025-02-21T20:17:13.249656+00:00', '--job-id', '1051', '--raw', '--subdir', 'DAGS_FOLDER/23_hooks_postgres_dag.py', '--cfg-path', '/tmp/tmpoiy56azh']
[2025-02-21T20:18:29.655+0000] {standard_task_runner.py:105} INFO - Job 1051: Subtask print_result_task
[2025-02-21T20:18:29.704+0000] {task_command.py:467} INFO - Running <TaskInstance: hooks.print_result_task manual__2025-02-21T20:17:13.249656+00:00 [running]> on host 70b8189021ad
[2025-02-21T20:18:29.805+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hooks' AIRFLOW_CTX_TASK_ID='print_result_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T20:17:13.249656+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T20:17:13.249656+00:00'
[2025-02-21T20:18:29.806+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T20:18:29.838+0000] {logging_mixin.py:190} INFO - Resultado da consulta
[2025-02-21T20:18:29.838+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/23_hooks_postgres_dag.py", line 37, in print_result
    for row in task_instance:
               ^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
[2025-02-21T20:18:29.847+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=hooks, task_id=print_result_task, run_id=manual__2025-02-21T20:17:13.249656+00:00, execution_date=20250221T201713, start_date=20250221T201829, end_date=20250221T201829
[2025-02-21T20:18:29.873+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T20:18:29.874+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1051 for task print_result_task ('NoneType' object is not iterable; 309)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/23_hooks_postgres_dag.py", line 37, in print_result
    for row in task_instance:
               ^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
[2025-02-21T20:18:29.915+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-21T20:18:29.932+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-21T20:18:29.934+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
